{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "v-server.serviceAccountName" . }}
  labels:
{{ include "v-server.labels" . | indent 4 }}
{{- end -}}
